version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"    
      MODE: "survival"
      VERSION: 1.12
      ONLINE-MODE: "false"
